#!/bin/bash

wget -c https://d4twhgtvn0ff5.cloudfront.net/caa-rechecking-incident-affected-serials.txt.gz

zcat < caa-rechecking-incident-affected-serials.txt.gz|sed -e 's:^serial ::g' -e 's: .*::g'> lecaa-serials.txt
